# Generated by Django 5.2 on 2025-05-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_date', models.DateField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('paragraph', models.TextField(max_length=1000)),
            ],
        ),
    ]
